spring:
  profiles:
    group:
      "local": "embeddedDB,oauth"
      "build": "embeddedDB,oauth"

---

spring:
  config:
    activate:
      on-profile: "embeddedDB"
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: "oauth"
  security:
      oauth2:
        client:
          registration:
            google:
              client-id: ${google_client_id}
              client-secret: ${google_client_secret}
              scope:
                - profile
                - email
---