spring:
  profiles:
    active: ${profile}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: ${ddl_auto}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${client_id}
            client-secret: ${client_secret}
            scope:
              - profile
              - email