spring:
  profiles:
    group:
      "local": "embeddedDB,oauth"
      "build": "embeddedDB,oauth"
      "app" : "realDB, oauth, web"

---

spring:
  config:
    activate:
      on-profile: "embeddedDB"
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect

---

spring:
  config:
    activate:
      on-profile: "realDB"
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  datasource:
    url: ${datasource_url}
    username: ${datasource_username}
    password: ${datasource_password}
    driver-class-name: com.mysql.cj.jdbc.Driver


---

spring:
  config:
    activate:
      on-profile: "oauth"
  security:
      oauth2:
        client:
          registration:
            google:
              client-id: ${google_client_id}
              client-secret: ${google_client_secret}
              scope:
                - profile
                - email

---

spring:
  config:
    activate:
      on-profile: "web"
server:
  tomcat:
    use-relative-redirects: true