name: techview CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: gradlew 실행 권한 부여
        run: chmod +x ./gradlew
        shell: bash

      - name: Gradle 빌드
        run: ./gradlew clean build
        shell: bash
        env:
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          SPRING_PROFILES_ACTIVE: build

      - name: 배포 파일 설정
        run: |
          mkdir -p deploy
          cp build/libs/*.jar deploy/application.jar
          cd deploy && zip -r deploy.zip .

      - name: AWS EB 배포
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: techview
          environment_name: Techview-env
          version_label: 12345
          region: ap-northeast-2
          deployment_package: deploy/deploy.zip